defaults:
  - data: default
  - training: default
  - prediction: default
  - trader : default
  - paths: default
  - _self_
 
step: train  # train | test | trade | stats 
frequency: 2m #1d
optuna:
  n_trials:   50
  max_epochs: 30
  batch_size: 64
  pruner:     hyperband      # median | hyperband
  storage:    sqlite:///hpo.db

